// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	database "tech-challenge-hackaton/internal/infra/database"

	mock "github.com/stretchr/testify/mock"
)

// ConnectionDBMock is an autogenerated mock type for the ConnectionDB type
type ConnectionDBMock struct {
	mock.Mock
}

type ConnectionDBMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionDBMock) EXPECT() *ConnectionDBMock_Expecter {
	return &ConnectionDBMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *ConnectionDBMock) Close() {
	_m.Called()
}

// ConnectionDBMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ConnectionDBMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ConnectionDBMock_Expecter) Close() *ConnectionDBMock_Close_Call {
	return &ConnectionDBMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ConnectionDBMock_Close_Call) Run(run func()) *ConnectionDBMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionDBMock_Close_Call) Return() *ConnectionDBMock_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectionDBMock_Close_Call) RunAndReturn(run func()) *ConnectionDBMock_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function with given fields: sql, args
func (_m *ConnectionDBMock) Exec(sql string, args ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(sql, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionDBMock_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type ConnectionDBMock_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - sql string
//   - args ...interface{}
func (_e *ConnectionDBMock_Expecter) Exec(sql interface{}, args ...interface{}) *ConnectionDBMock_Exec_Call {
	return &ConnectionDBMock_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{sql}, args...)...)}
}

func (_c *ConnectionDBMock_Exec_Call) Run(run func(sql string, args ...interface{})) *ConnectionDBMock_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ConnectionDBMock_Exec_Call) Return(_a0 error) *ConnectionDBMock_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionDBMock_Exec_Call) RunAndReturn(run func(string, ...interface{}) error) *ConnectionDBMock_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: sql, args
func (_m *ConnectionDBMock) Query(sql string, args ...interface{}) (database.RowsDB, error) {
	var _ca []interface{}
	_ca = append(_ca, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 database.RowsDB
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (database.RowsDB, error)); ok {
		return rf(sql, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) database.RowsDB); ok {
		r0 = rf(sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.RowsDB)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectionDBMock_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type ConnectionDBMock_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - sql string
//   - args ...interface{}
func (_e *ConnectionDBMock_Expecter) Query(sql interface{}, args ...interface{}) *ConnectionDBMock_Query_Call {
	return &ConnectionDBMock_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{sql}, args...)...)}
}

func (_c *ConnectionDBMock_Query_Call) Run(run func(sql string, args ...interface{})) *ConnectionDBMock_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ConnectionDBMock_Query_Call) Return(_a0 database.RowsDB, _a1 error) *ConnectionDBMock_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectionDBMock_Query_Call) RunAndReturn(run func(string, ...interface{}) (database.RowsDB, error)) *ConnectionDBMock_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: sql, args
func (_m *ConnectionDBMock) QueryRow(sql string, args ...interface{}) database.RowDB {
	var _ca []interface{}
	_ca = append(_ca, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 database.RowDB
	if rf, ok := ret.Get(0).(func(string, ...interface{}) database.RowDB); ok {
		r0 = rf(sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(database.RowDB)
		}
	}

	return r0
}

// ConnectionDBMock_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type ConnectionDBMock_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - sql string
//   - args ...interface{}
func (_e *ConnectionDBMock_Expecter) QueryRow(sql interface{}, args ...interface{}) *ConnectionDBMock_QueryRow_Call {
	return &ConnectionDBMock_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{sql}, args...)...)}
}

func (_c *ConnectionDBMock_QueryRow_Call) Run(run func(sql string, args ...interface{})) *ConnectionDBMock_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *ConnectionDBMock_QueryRow_Call) Return(_a0 database.RowDB) *ConnectionDBMock_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionDBMock_QueryRow_Call) RunAndReturn(run func(string, ...interface{}) database.RowDB) *ConnectionDBMock_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectionDBMock creates a new instance of ConnectionDBMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionDBMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionDBMock {
	mock := &ConnectionDBMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
