// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	httpserver "tech-challenge-hackaton/internal/infra/http"

	mock "github.com/stretchr/testify/mock"
)

// HTTPHandlerFuncMock is an autogenerated mock type for the HTTPHandlerFunc type
type HTTPHandlerFuncMock struct {
	mock.Mock
}

type HTTPHandlerFuncMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HTTPHandlerFuncMock) EXPECT() *HTTPHandlerFuncMock_Expecter {
	return &HTTPHandlerFuncMock_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *HTTPHandlerFuncMock) Execute(_a0 httpserver.HTTPContext) {
	_m.Called(_a0)
}

// HTTPHandlerFuncMock_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type HTTPHandlerFuncMock_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 httpserver.HTTPContext
func (_e *HTTPHandlerFuncMock_Expecter) Execute(_a0 interface{}) *HTTPHandlerFuncMock_Execute_Call {
	return &HTTPHandlerFuncMock_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *HTTPHandlerFuncMock_Execute_Call) Run(run func(_a0 httpserver.HTTPContext)) *HTTPHandlerFuncMock_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(httpserver.HTTPContext))
	})
	return _c
}

func (_c *HTTPHandlerFuncMock_Execute_Call) Return() *HTTPHandlerFuncMock_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *HTTPHandlerFuncMock_Execute_Call) RunAndReturn(run func(httpserver.HTTPContext)) *HTTPHandlerFuncMock_Execute_Call {
	_c.Run(run)
	return _c
}

// NewHTTPHandlerFuncMock creates a new instance of HTTPHandlerFuncMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHTTPHandlerFuncMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HTTPHandlerFuncMock {
	mock := &HTTPHandlerFuncMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
