FROM golang:1.23.5-alpine3.21

ENV PROJECT_DIR=/consumer \
    GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux

RUN apk add --no-cache ffmpeg

WORKDIR /consumer

# Download Go modules
COPY . .

RUN go mod download

RUN go build -o build/consumer cmd/consumer/main.go

CMD [ "build/consumer" ] 
