apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tech-challenge-hackaton-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tech-challenge-hackaton-api-deployment
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

