apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-hackaton-api-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: tech-challenge-hackaton-api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
