apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-hackaton-api-nodeport
spec:
  type: NodePort
  selector:
    app: tech-challenge-hackaton-api-deployment
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30003
